var verbs50 = [
"быть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>be [bi:] (am, is, are) - was [wɔz] / were [wз:]", 
"иметь</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>have [hæv] - had [hæd]", 
"делать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>do [du:] - did [did]", 
"говорить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>say [sei] - said [sed]", 
"идти</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>go [gou] - went [went]", 
"мочь; уметь</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>can [kæn] - could [kud]", 
"смотреть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>look [luk] - looked [lukt]", 
"знать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>know [nəu] - knew [nju:]", 
"получать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>get [get] - got [gɔt]", 
"приходить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>come [kʌm] - came [keim]", 
"видеть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>see [si:] - saw [sɔ:]", 
"вспомогательный глагол, завещать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>will [wil] - would [wud]", 
"думать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>think [θiŋk] - thought [θɔ:t]", 
"делать, изготавливать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>make [meik] - made [meid]", 
"хотеть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>want [wɔnt] - wanted [wɔntid]", 
"поворачиваться, вращаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>turn [tз:n] - turned [tз:nd]", 
"казаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>seem [si:m] - seemed [si:md]", 
"звонить, звать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>call [kɔ:l] - called [kɔ:ld]", 
"спрашивать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>ask [a:sk] - asked [a:skt]", 
"вспомогательный глагол</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shall [ʃæl] - should [ʃud]", 
"позволять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>let [let] - let [let]", 
"брать, взять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>take [teik] - took [tuk]", 
"рассказывать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>tell [tel] - told [tould]", 
"любить, нравится</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>like [laik] - liked [laikt]", 
"мочь</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>may [mei] - might [mait]", 
"должен</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>must [mʌst] - ", 
"работать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>work [wз:k] - worked [wз:kt]", 
"положить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>put [put] - put [put]", 
"открыть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>open ['əup(ə)n] - opened ['əup(ə)nd]", 
"чувствовать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>feel [fi:l] - felt [felt]", 
"давать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>give [giv] - gave [geiv]", 
"любить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>love [lʌv] - loved [lʌvd]", 
"находить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>find [faind] - found [faund]", 
"начинать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>begin [bi'gin] - began [bi'gæn]", 
"слышать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>hear [hiə] - heard [hз:d]", 
"нуждаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>need [ni:d] - needed [ni:did]", 
"пробовать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>try [trai] - tryed [traid]", 
"гулять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>walk [wɔ:k] - walked [wɔ:kt]", 
"помнить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>remember [ri'membə] - remembered [ri'membəd]", 
"покидать, уезжать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>leave [li:v] - left [left]", 
"случаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>happen ['hæp(ə)n] - happened ['hæp(ə)nd]", 
"говорить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>talk [tɔ:k] - talked [tɔ:kt]", 
"стоять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>stand [stænd] - stood [stu:d]", 
"использовать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>use [ju:z] - used [ju:zid]", 
"начинать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>start [sta:t] - started [sta:tid]", 
"держать, хранить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>keep [ki:p] - kept [kept]", 
"плакать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>cry [krai] - cryed [krad]", 
"жить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>live [liv] - lived [livd]", 
"останавливаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>stop [stɔp] - stopped [stɔpt]", 
"закрывать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>close [kləuz] - closed [kləuzt]"
];
