var adjs50 = [
"другой, иной</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>other ['ʌðə]", 
"маленький</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>little ['litl]", 
"правый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>right [rait]", 
"хороший</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>good [gud]", 
"какой-нибудь</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>any ['eni]", 
"старый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>old [əuld]", 
"больший</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>more [mɔ:]", 
"первый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>first [fз:st]", 
"длинный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>long [lɔŋ]", 
"последний</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>last [la:st]", 
"большой, великий</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>great [greit]", 
"белый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>white [(h)wait]", 
"другой</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>another [ə'nʌðə]", 
"тот же самый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>same [seim]", 
"новый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>new [nju:]", 
"тихий</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>still [stil]", 
"большой</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>big [big]", 
"каждый, всякий</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>every ['evri]", 
"лучший, наилучший</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>better ['betə]", 
"каждый, всякий</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>each [i:tʃ]", 
"черный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>black [blæk]", 
"красный, алый, рыжий</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>red [red]", 
"молодой, юный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>young [jʌŋ]", 
"следующий; будущий</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>next [nekst]", 
"тёмный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>dark [da:k]", 
"маленький</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>small [smɔ:l]", 
"жёсткий, твёрдый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>hard [ha:d]", 
"минимальный, наименьший</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>least [li:st]", 
"высокий</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>high [hai]", 
"плохой</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bad", 
"серый, седой</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>gray [grei]", 
"использованный, старый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>used [ju:zd]", 
"весь, целый; полный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>whole [həul]", 
"реальный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>real [riəl]", 
"свой; собственный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>own [əun]", 
"самый лучший, наилучший</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>best [best]", 
"холодный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>cold [kəuld]", 
"милый, прелестный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>pretty ['priti]", 
"дальний</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>far [fa:]", 
"единственный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>alone [ə'ləun]", 
"дорогой, милый, любимый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>dear [diə]", 
"глубокий</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>deep [di:p]", 
"зелёный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>green [gri:n]", 
"уверенный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sure [ʃuə]", 
"круглый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>round [raund]", 
"чистый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>clear [kliə]", 
"один из двух; тот или другой</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>either ['aiðə]", 
"мертвый</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>dead [ded]", 
"сделанный; выполненный</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>done [dʌn]", 
"второй</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>second ['sek(ə)nd]"
];
