var verbs174 = [
"возникать, появляться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>arise [ə`raɪz] - arose [ə`roʊz] - arisen [ə`rɪzn]", 
"будить, просыпаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>awake [ə`waɪk] - awoke [ə`woʊk] - awoken [ə`woʊkn]", 
"быть, находиться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>be [bi:] - was; were [wɒz], [wɜ:] - been [bi:n]", 
"носить, выносить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bear [bɛə] - bore [bɔ:] - borne [bɔ:n]", 
"бить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>beat [bi:t] - beat [bi:t] - beaten [bi:tn]", 
"становиться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>become [bɪ`kʌm] - became [bɪ`keɪm] - become [bɪ`kʌm]", 
"начинать(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>begin [bɪ`gɪn] - began [bɪ`gæn] - begun [bɪ`gʌn]", 
"гнуть(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bend [bend] - bent [bent] - bent [bent]", 
"держать пари</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bet [bet] - bet [bet] - bet [bet]", 
"велеть, просить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bid [bɪd] - bid/bade [bɪd/beɪd] - bidden [bɪdn]", 
"предлагать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bid [bɪd] - bid [bɪd] - bid [bɪd]", 
"связывать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bind [baɪnd] - bound [baʊnd] - bound [baʊnd]", 
"кусать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bit [bɪt] - bit [bɪt] - bitten [bɪtn]", 
"кровоточить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bleed [bli:d] - bled [bled] - bled [bled]", 
"дуть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>blow [bloʊ] - blew [blu:] - blown [blu:]", 
"ломать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>break [breɪk] - broke [broʊk] - broken [broʊkən]", 
"разводить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>breed [bri:d] - bred [bred] - bred [bred]", 
"принести</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bring [brɪŋ] - brought [brɔ:t] - brought [brɔ:t]", 
"строить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>build [bɪld] - built [bɪlt] - built [bɪlt]", 
"жечь, гореть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>burn [bɜ:n] - burned/burnt [bɜ:nd/bɜ:nd] - burned/burnt [bɜ:nd/bɜ:nd]", 
"взорваться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>burst [bɜ:st] - burst [bɜ:st] - burst [bɜ:st]", 
"разорить(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bust [bʌst] - busted/bust [bʌstɪd/bʌst] - busted/bust [bʌstɪd/bʌst]", 
"купить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>buy [baɪ] - bought [bɔ:t] - bought [bɔ:t]", 
"держать пари</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>bet - bet - bet", 
"бросать, кидать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>cast [kɑ:st] - cast [kɑ:st] - cast [kɑ:st]", 
"ловить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>catch [kætʃ] - caught [kɔ:t] - caught [kɔ:t]", 
"выбирать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>choose [tʃu:z] - chose [tʃoʊz] - chosen [tʃoʊzn]", 
"рассечь</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>cleave [kli:v] - cleft [klieft] - cleft [klieft]", 
"цеплять(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>cling [klɪŋ] - clung [klʌŋ] - clung [klʌŋ]", 
"одеть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>clothe [kloʊð] - clothed/clad [kloʊðd/klæd] - clothed/clad [kloʊðd/klæd]", 
"приходить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>come [kʌm] - came [keɪm] - come [keɪm]", 
"стоить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>cost [kɒst] - cost [kɒst] - cost [kɒst]", 
"ползать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>creep [kri:p] - crept [krept] - crept [krept]", 
"резать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>cut [kʌt] - cut [kʌt] - cut [kʌt]", 
"торговать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>deal [di:l] - dealt [delt] - dealt [delt]", 
"копать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>dig [dɪg] - dug [dʌg] - dug [dʌg]", 
"нырять, погружаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>dive [daɪv] - dove/dived [doʊv/daɪvd] - dived [daɪvd]", 
"делать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>do [du:] - did [dɪd] - done [dʌn]", 
"рисовать, тащить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>draw [drɔ:] - drew [dru:] - drawn [drɔ:n]", 
"видеть сны, мечтать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>dream [dri:m] - dreamed/dreamt [dri:md/dremt] - dreamed/dreamt [dri:md/dremt]", 
"пить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>drink [drɪnk] - drank [drænk] - drunk [drʌnk]", 
"водить, гнать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>drive [draɪv] - drove [droʊv] - driven [drɪvn]", 
"обитать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>dwell [dwel] - dwelt/dwelled [dwelt/dweld] - dwelt/dwelled [dwelt/dweld]", 
"кушать, есть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>eat [i:t] - ate [et] - eaten [i:tn]", 
"падать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>fall [fɔ:l] - fell [fel] - fallen [fɔ:lən]", 
"кормить(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>feed [fi:d] - fed [fed] - fed [fed]", 
"чувствовать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>feel [fi:l] - felt [felt] - felt [felt]", 
"бороться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>fight [faɪt] - fought [fɔ:t] - fought [fɔ:t]", 
"находить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>find [faɪnd] - found [faʊnd] - found [faʊnd]", 
"бежать, спасаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>flee [fli:] - fled [fled] - fled [fled]", 
"швырять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>fling [flɪŋ] - flung [flʌŋ] - flung [flʌŋ]", 
"летать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>fly [flaɪ] - flew [flu:] - flown [floʊn]", 
"запретить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>forbid [fə`bɪd] - forbade [fə`beɪd] - for`bidden [fəbɪdn]", 
"забыть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>forget [fə`get] - forgot [fə`gɒt] - forgotten [fə`gɒtn]", 
"простить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>forgive [fə`gɪv] - forgave [fə`geɪv] - for`given [fəgɪvn]", 
"покидать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>forsake [fə`seɪk] - forsook [fə`sʊk] - forsaken [fə`seɪkn]", 
"замерзать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>freeze [fri:z] - froze [froʊz] - frozen [froʊzn]", 
"получать, становиться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>get [get] - got [gɒt] - gotten/got [gɒtn/gɒt]", 
"позолотить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>gild [gɪld] - gilt [gɪlt] - gilt [gɪlt]", 
"давать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>give [gɪv] - gave [geɪv] - given [gɪvn]", 
"идти, ехать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>go [goʊ] - went [went] - gone [gɒ]", 
"точить, молоть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>grind [graɪnd] - ground [graʊnd] - ground [graʊnd]", 
"расти, выращивать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>grow [groʊ] - grew [gru:] - grown [groʊn]", 
"висеть, повесить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>hang [hæŋ] - hung [hʌŋ] - hung [hʌŋ]", 
"иметь</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>have [hæv] - had [hæd] - had [hæd]", 
"слышать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>hear [hɪə] - heard [hɜ:d] - heard [hɜ:d]", 
"рубить, тесать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>hew [hju:] - hewed [hju:d] - hewn [hju:n]", 
"прятать(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>hide [haɪd] - hid [hɪd] - hidden [hɪdn]", 
"ударить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>hit [hɪt] - hit [hɪt] - hit [hɪt]", 
"держать, проводить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>hold [hoʊld] - held [held] - held [held]", 
"ранить, обижать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>hurt [hɜ:t] - hurt [hɜ:t] - hurt [hɜ:t]", 
"держать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>keep [ki:p] - kept [kept] - kept [kept]", 
"становиться на колени</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>kneel [ni:l] - knelt [nelt] - knelt [nelt]", 
"вязать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>knit [nɪt] - knit [nɪt] - knit [nɪt]", 
"знать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>know [noʊ] - knew [nju:] - known [noʊn]", 
"класть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>lay [leɪ] - laid [leɪd] - laid [leɪd]", 
"вести</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>lead [li:d] - led [led] - led [led]", 
"опираться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>lean [li:nd] - leant [lent] - leant [lent]", 
"прыгать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>leap [li:p] - leapt [lept] - leapt [lept]", 
"учить(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>learn [lɜ:n] - learned/learnt [lɜ:nd/lɜ:nt] - learnt [lɜ:nt]", 
"оставлять, уезжать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>leave [li:v] - left [left] - left [left]", 
"давать взаймы</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>lend [lend] - lent [lent] - lent [lent]", 
"позволять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>let [let] - let [let] - let [let]", 
"лежать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>lie [laɪ] - lay [leɪ] - lain [leɪn]", 
"терять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>lose [lu:z] - lost [lɒst] - lost [lɒst]", 
"зажигать, освещать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>light [laɪt] - lit/lighted [lɪt/laɪtɪd] - lit/lighted [lɪt/laɪtɪd]", 
"делать, создавать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>make [meɪk] - made [meɪd] - made [meɪd]", 
"значить, подразумевать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>mean [mi:n] - meant [ment] - meant [ment]", 
"встретить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>meet [mi:t] - met [met] - met [met]", 
"косить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>mow [moʊ] - mowed [moʊd] - mown [moʊn]", 
"платить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>pay [peɪ] - paid [peɪd] - paid [peɪd]", 
"заявлять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>plead [pli:d] - pleaded/pled [pli:dɪd/pled] - pleaded/pled [pli:dɪd/pled]", 
"доказывать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>prove [pru:v] - proved [pru:vd] - proven/proved [pru:vən/pru:vd]", 
"класть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>put [pʊt] - put [pʊt] - put [pʊt]", 
"читать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>read [ri:d] - read [red] - read [red]", 
"избавлять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>rid [rɪd] - rid [rɪd] - rid [rɪd]", 
"ездить верхом</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>ride [raɪd] - rode [roʊd] - ridden [rɪdn]", 
"звонить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>ring [rɪŋ] - rang [ræŋ] - rung [rʌŋ]", 
"подниматься</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>rise [raɪz] - rose [roʊz] - risen [rɪzn]", 
"бежать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>run [rʌn] - ran [ræn] - run [rʌn]", 
"пилить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>saw [sɔ:] - sawed [sɔ:d] - sawed/sawn [sɔ:d/sɔ:n]", 
"сказать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>say [seɪ] - said [sed] - said [sed]", 
"видеть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>see [si:] - saw [sɔ:] - seen [si:n]", 
"искать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>seek [si:k] - sought [sɔ:t] - sought [sɔ:t]", 
"продавать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sell [sel] - sold [soʊld] - sold [soʊld]", 
"послать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>send [send] - sent [sent] - sent [sent]", 
"ставить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>set [set] - set [set] - set [set]", 
"шить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sew [soʊ] - sewed [soʊd] - sewn [soʊn]", 
"трясти</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shake [ʃeɪk] - shook [ʃʊk] - shaken [ʃeɪkən]", 
"брить(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shave [ʃeɪv] - shaved [ʃeɪvd] - shaved/shaven [ʃeɪvd/ʃeɪvən]", 
"стричь</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shear [ʃɪə] - sheared [ʃɪəd] - sheared/shorn [ʃɪəd/ʃɔ:n]", 
"проливать (слёзы)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shed [ʃed] - shed [ʃed] - shed [ʃed]", 
"светить, сиять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shine [ʃaɪn] - shone [ʃoʊn] - shone [ʃoʊn]", 
"обувать, подковывать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shoe [ʃu:] - shod [ʃɒd] - shod [ʃɒd]", 
"стрелять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shoot [ʃu:t] - shot [ʃɒt] - shot [ʃɒt]", 
"показывать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>show [ʃoʊ] - showed [ʃoʊd] - shown [ʃoʊn]", 
"сжиматься</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shrink [ʃrɪŋk] - shrank [ʃræŋk] - shrunk [ʃrʌŋk]", 
"закрывать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>shut [ʃʌt] - shut [ʃʌt] - shut [ʃʌt]", 
"петь</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sing [sɪŋ] - sang [sæŋ] - sung [sʌŋ]", 
"погружаться, тонуть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sink [sɪŋk] - sank [sæŋk] - sunk [sʌŋk]", 
"сидеть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sit [sɪt] - sat [sæt] - sat [sæt]", 
"убивать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>slay [sleɪ] - slew/slayed [slu:/sleɪd] - slain/slayed [sleɪn/sleɪd]", 
"спать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sleep [sli:p] - slept [slept] - slept [slept]", 
"скользить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>slide [slaɪd] - slid [slɪd] - slid [slɪd]", 
"метать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sling [slɪŋ] - slung [slʌŋ] - slung [slʌŋ]", 
"красться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>slink [slɪŋk] - slinked/slunk [slɪŋkt/slʌŋk] - slinked/slunk [slɪŋkt/slʌŋk]", 
"пахнуть, нюхать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>smell [smel] - smelt [smelt] - smelt [smelt]", 
"сеять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sow [soʊ] - sowed [soʊd] - sown [soʊn]", 
"говорить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>speak [spi:k] - spoke [spoʊk] - spoken [spoʊkən]", 
"мчаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>speed [spi:d] - sped [sped] - sped [sped]", 
"писать, читать по буквам</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>spell [spel] - spelt [spelt] - spelt [spelt] ", 
"тратить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>spend [spend] - spent [spent] - spent [spent]", 
"расплескать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>spill [spɪl] - spilt [spɪlt] - spilt [spɪlt]", 
"прясть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>spin [spɪn] - spun [spʌn] - spun [spʌn]", 
"плевать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>spit [spɪt] - spit/spat [spɪt/spæt] - spit/spat [spɪt/spæt]", 
"расщепить(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>split [splɪt] - split [splɪt] - split [splɪt]", 
"портить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>spoil [spoɪl] - spoiled/spoilt [spoɪld/spoɪlt] - spoiled/spoilt [spoɪld/spoɪlt]", 
"распространиться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>spread [spred] - spread [spred] - spread [spred]", 
"возникнуть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>spring [sprɪŋ] - sprang [spræŋ] - sprung [sprʌŋ]", 
"стоять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>stand [stænd] - stood [stʊd] - stood [stʊd]", 
"красть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>steal [sti:l] - stole [stoʊl] - stolen [stoʊlən]", 
"липнуть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>stick [stɪk] - stuck [stʌk] - stuck [stʌk]", 
"жалить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sting [stɪŋ] - stung [stʌŋ] - stung [stʌŋ]", 
"вонять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>stink [stɪŋk] - stank [stræŋk] - stunk [stʌŋk]", 
"усеять</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>strew [str:] - strewed [str:d] - strewn [str:n]", 
"шагать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>stride [straɪd] - strode [stroʊd] - stridden [strɪdn]", 
"ударить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>strike [straɪk] - struck [strʌk] - struck/stricken [strʌk/strɪkən]", 
"нанизать, натянуть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>string [strɪŋ] - strung [srtʌŋ] - strung [strʌŋ]", 
"стараться, стремиться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>strive [straɪv] - strove/strived [stroʊv/straɪvd] - striven/strived [strɪvən/straɪvd]", 
"клясться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>swear [swɛə] - swore [swɔ:] - sworn [swɔ:n]", 
"потеть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sweat [swet] - sweat/sweated [swet/[swetɪd] - sweat/sweated [swet/swetɪd]", 
"мести</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>sweep [swi:p] - swept [swept] - swept [swept]", 
"вздуться, раздуваться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>swell [swel] - swelled [sweld] - swollen/swelled [swoʊlən/sweld]", 
"плыть</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>swim [swɪm] - swam [swæm] - swum [swʌm]", 
"качаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>swing [swɪŋ] - swung [swʌŋ] - swung [swʌŋ]", 
"взять, брать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>take [teɪk] - took [tʊk] - taken [teɪkən]", 
"обучать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>teach [ti:tʃ] - taught [tɔ:t] - taught [tɔ:t]", 
"рвать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>tear [tɛə] - tore [tɔ:] - torn [tɔ:n]", 
"рассказывать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>tell [tel] - told [toʊld] - told [toʊld]", 
"думать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>think [θɪŋk] - thought [θɔ:t] - thought [θɔ:t]", 
"бросать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>throw [θroʊ] - threw [θru:] - thrown [θroʊn]", 
"толкать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>thrust [θrʌst] - thrust [θrʌst] - thrust [θrʌst]", 
"ступать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>tread [tred] - trod [trɒd] - trodden [trɒdn]", 
"понимать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>understand [ʌndə`stænd] - understood [ʌndə`stʊd] - understood [ʌndə`stʊd]", 
"просыпаться</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>wake [weɪk] - woke/waked [woʊk/weɪkt] - woken/waked [woʊkən/weɪkt]", 
"носить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>wear [wɛə] - wore [wɔ:] - worn [wɔ:n]", 
"ткать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>weave [wi:v] - wove/weaved [woʊv/wi:vd] - woven/weaved [woʊvən/wi:vd]", 
"вступать в брак</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>wed [wed] - wed/wedded [wed/wedɪd] - wed/wedded [wed/wedɪd]", 
"плакать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>weep [wi:p] - wept [wept] - wept [wept]", 
"мочить</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>wet [wet] - wet [wet] - wet [wet]", 
"выигрывать, побеждать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>win [wɪn] - won [wʌn] - won [wʌn]", 
"виться(ся)</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>wind [waɪnd] - wound [waʊnd] - wound [waʊnd]", 
"выкручивать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>wring [rɪŋ] - wrung [rʌŋ] - wrung [rʌŋ]", 
"писать</td></tr><tr><td class=ab>Спойлер:</td><td class=spo>write [raɪt] - wrote [roʊt] - written [rɪtn]"
];
